services:
#    dglas_caisse.example:
#        class: Dglas\CaisseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    dglas_caisse.admin.caisse:
        class: Dglas\CaisseBundle\Admin\CaisseAdmin
        arguments: [~, Dglas\CaisseBundle\Entity\Caisse, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 'Caisse journaliere' }


        
