<?php

namespace Dglas\AnimateurBundle\Repository;

/**
 * AnimateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimateurRepository extends \Doctrine\ORM\EntityRepository
{
}
