<?php

namespace Dglas\CaisseBundle\Repository;

/**
 * CaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaisseRepository extends \Doctrine\ORM\EntityRepository
{
}
