<?php

namespace Dglas\JeuBundle\Repository;

/**
 * EtatJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatJeuRepository extends \Doctrine\ORM\EntityRepository
{

}
