<?php

namespace Dglas\JeuBundle\Repository;

/**
 * GestionnaireJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionnaireJeuRepository extends \Doctrine\ORM\EntityRepository
{
}
