<?php

namespace Dglas\JeuBundle\Repository;

/**
 * InventaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventaireRepository extends \Doctrine\ORM\EntityRepository
{
}
