<?php

namespace Dglas\JeuBundle\Repository;

/**
 * JeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeuRepository extends \Doctrine\ORM\EntityRepository
{
}
