<?php

namespace Dglas\JeuBundle\Repository;

/**
 * LieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuRepository extends \Doctrine\ORM\EntityRepository
{
}
