<?php

namespace Dglas\JeuBundle\Repository;

/**
 * LigneReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
