<?php

namespace Dglas\JeuBundle\Repository;

/**
 * MouvementJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementJeuRepository extends \Doctrine\ORM\EntityRepository
{
}
