<?php

namespace Dglas\JeuBundle\Repository;

/**
 * NommenclatureEtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NommenclatureEtatRepository extends \Doctrine\ORM\EntityRepository
{
}
