<?php

namespace Dglas\JeuBundle\Repository;

/**
 * NommenclatureJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NommenclatureJeuRepository extends \Doctrine\ORM\EntityRepository
{
}
