services:
#    dglas_jeu.example:
#        class: Dglas\JeuBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    dglas_jeu.admin.nommenclature_jeu:
        class: Dglas\JeuBundle\Admin\NommenclatureJeuAdmin
        arguments: [~, Dglas\JeuBundle\Entity\NommenclatureJeu, DglasJeuBundle:NommenclatureJeuAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Reference des jeux }

    dglas_jeu.admin.etat_jeu:
        class: Dglas\JeuBundle\Admin\EtatJeuAdmin
        arguments: [~, Dglas\JeuBundle\Entity\EtatJeu, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Etat d'un jeu }
        public: true

    dglas_jeu.admin.proprietaire:
        class: Dglas\JeuBundle\Admin\ProprietaireAdmin
        arguments: [~, Dglas\JeuBundle\Entity\Proprietaire, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Proprietaire }
        public: true

    dglas_jeu.admin.nommenclature_etat:
        class: Dglas\JeuBundle\Admin\NommenclatureEtatAdmin
        arguments: [~, Dglas\JeuBundle\Entity\NommenclatureEtat, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Nomenclature des états de jeu }
        public: true

    dglas_jeu.admin.extensions.jeu:
        class: Dglas\JeuBundle\Admin\Extension\JeuAdminExtensionInterface
        arguments: ["@sonata.admin.entity_manager"]

    dglas_jeu.admin.extensions.inventaire:
        class: Dglas\JeuBundle\Admin\Extension\InventaireAdminExtensionInterface
        arguments: ["@sonata.admin.entity_manager"]

    dglas_jeu.admin.jeu:
        class: Dglas\JeuBundle\Admin\JeuAdmin
        arguments: [~, Dglas\JeuBundle\Entity\Jeu, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Boite de jeu }
        public: true
        calls:
            - method: "addExtension"
              arguments:
                - "@dglas_jeu.admin.extensions.jeu"

    dglas_jeu.admin.gestionnaire_jeu:
        class: Dglas\JeuBundle\Admin\GestionnaireJeuAdmin
        arguments: [~, Dglas\JeuBundle\Entity\GestionnaireJeu, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Gestionnaire des jeux }
        public: true

    dglas_jeu.admin.lieu:
        class: Dglas\JeuBundle\Admin\LieuAdmin
        arguments: [~, Dglas\JeuBundle\Entity\Lieu, DglasJeuBundle:LieuAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Lieux de stockage }
        public: true

    dglas_jeu.admin.mouvement_jeu:
        class: Dglas\JeuBundle\Admin\MouvementJeuAdmin
        arguments: [~, Dglas\JeuBundle\Entity\MouvementJeu, DglasJeuBundle:MouvementJeuAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Mouvements }
        public: true

    dglas_jeu.admin.animateur:
        class: Dglas\JeuBundle\Admin\AnimateurAdmin
        arguments: [~, Dglas\JeuBundle\Entity\Animateur, DglasJeuBundle:AnimateurAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Animateur }
        public: true

    dglas_jeu.admin.inventaire:
        class: Dglas\JeuBundle\Admin\InventaireAdmin
        arguments: [~, Dglas\JeuBundle\Entity\Inventaire, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Inventaire }
        public: true
        calls:
            - method: "addExtension"
              arguments:
                - "@dglas_jeu.admin.extensions.inventaire"
